# file: .github/workflows/hello.yml
name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # say – произвольно выбранное имя задания
  # их может быть больше одного
  say:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v2
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      # - run: ls -la
      - run: make say-hello
